### ISSUE TITLE
A better way to unblock Quora

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/quora-unblocker#4]
I propose another ways to unblock Quora:

1. Remove `Referer` header.
2. Disable these styles: 

```css
.signup_wall_prevent_scroll {
	overflow: hidden;
}

.signup_wall_prevent_scroll .SiteHeader,
.signup_wall_prevent_scroll .LoggedOutFooter,
.signup_wall_prevent_scroll .ContentWrapper {
	filter: blur(3px);
}
```

And remove `#__w2_XXXXXXXX_signup_wall_wrapper` (each X can be a different character).
